### ISSUE TITLE
Redux-saga compatibility

### ISSUE THREAD

**Issue by sneas** [Hotell/rex-tils#21]
Hi @Hotell, thanks a lot for the library. It provides the best typesafe Redux + Typescript FSA solution (as far as I can see).

Unfortunately it does not work with Redux-saga as expected.

The problem is `createAction()` function returns frozen object in `DEV` environment, but Saga does `Object.defineProperty(action, SAGA_ACTION, { value: true })` which leads to an exception:

```
TypeError: Cannot define property @@redux-saga/SAGA_ACTION, object is not extensible
```

For now I solve this problem by 'unfreezing' the action: `yield put({...Actions.fetchSuccess(data)})`.

But my question is do we really need to return frozen action object with `createAction()`? I understand it provides more 'safe-to-be-used' FSA, but on the other hand this solution conflicts with quite a popular Redux tool.

**Comment by JamesAlias** [comment]
I came across the same issue.

Imho it is Redux Saga's _"fault"_ to not work immutable. Then again I don't exactly know _why_ they choose to use `Object.defineProperty` in favor of the likes of `Object.assign`. The only significant difference afaik is that the property defined with `Object.defineProperty` is not _enumerable_ by default. That means the defined property will not be available in a for..in loop for example.

**My fix was to use Redux-Observables (Epics).** While I kind of like the rather imperative declaration of async action handlers via generators - I think that functional, reactive action handlers via observables/streams is what the community is leaning towards (for good reasons, tbh).

**Comment by sneas** [comment]
Thanks for your reply, @JamesAlias. I suppose Saga uses `Object.defineProperty` instead of `Object.assign` in order not to expose it's action's modifications to Redux Dev Tools...

I've also decided to switch to Redux-Observables.

Will close the issue even though I still believe redux-saga compatibility could be beneficial for the project by increasing it's popularity.

**Comment by Hotell** [comment]
Hey folks! thanks for the report. I'm usually afk during weekends. 

I've personally never used redux-saga for various reason ( not the right tool for the right job,... debugging generators ouch etc ). Now I'm even more against it if it does this weird thing with defineProperty that you described.

I could remove that object freeze if there will be more people requesting it but as I see it redux-observable all the side effect things.

Cheers folks !

**Comment by navneet-g** [comment]
@Hotell Please remove object freeze, we use redux-saga.

**Comment by Hotell** [comment]
@navneet-g  feel free to send a PR 👌🤙

**Comment by navneet-g** [comment]
Sure ... will do :)
