### ISSUE TITLE
Get the type of a single action

### ISSUE THREAD

**Issue by abettadapur** [Hotell/rex-tils#3]
I find these utilities very useful in most cases, so thanks for putting them out there!

My project makes use of the `redux-saga` library. One issue we run into frequently is the ability to get the type of a single action, instead of the union of all the actions. For example, our saga code might look like this:

```ts
/// FooActions.ts
export const enum FooActionTypes {
    FooAction = "FooAction"
}

export const FooActions = {
    fooAction: (payload: IComplexPayload) => createAction(FooActionTypes.FooAction, payload)
}

export type FooActions = ActionsUnion<typeof FooActions>;


// Saga.ts
yield takeEvery(FooActionTypes.fooAction, processFooAction)

/*!!! can't type this properly, the payload type can be anything */
function* processFooAction(action: ActionWithPayload<FooActionTypes.FooAction, IWrongPayload> ) {
    ...
}
```
I would like to type the FooAction directly.
Do you have any suggestions on how I might accomplish this?

**Comment by Hotell** [comment]
Hey @abettadapur !

I've submitted a PR which should give you what you need. Can you review it please ? 

Cheers

**Comment by Hotell** [comment]
Released https://github.com/Hotell/rex-tils/blob/master/CHANGELOG.md#050-2018-08-16 thanks for review ! 🍻
